### ISSUE TITLE
Não consigo migrar meu projeto THF

### ISSUE THREAD

**Issue by ratsclub** [portinariui/po-migration#1]
Estou tentando migrar um projeto inicializado através do [desse guia](https://thf.totvs.com.br/guides/getting-started) do Portal THF. O erro retornado é:

```
ATENÇÃO:  Não foi possível realizar a conversão!
É necessário que o projeto esteja com a versão 4 do THF.
```

**Dependências**
 ```json
"dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/platform-server": "~8.0.0",
    "@angular/router": "~8.0.0",
    "@totvs/thf-ui": "^4.0.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  }
```

**Comment by alvarocamillont** [comment]
Você instalou e se certificou que o projeto está funcionando no thf 4?

**Comment by ratsclub** [comment]
Sim, sim. Acabei de mandar um PR contendo um pedaço de código que pode estar causando esse problema. #3

**Comment by alvarocamillont** [comment]
Estranho pq eu migrei de boa...

**Comment by ratsclub** [comment]
Se eu remover o ``^`` da linha ``"@totvs/thf-ui": "^4.0.0"`` em minhas dependências o migrador funciona.

**Comment by alvarocamillont** [comment]
Hummmmm é parece realmente erro do regex que vc mandou no pr :)

**Comment by ratsclub** [comment]
![image](https://user-images.githubusercontent.com/25647735/60368892-6c3da900-99c8-11e9-9cbf-77611888a998.png)

Sem a correção nos é retornado o seguinte erro.

**Comment by jhonyeduardo** [comment]
Boa tarde Victor, obrigado por reportar esta issue.

Atualizamos o pacote **po-migration@1.0.2** com a correção deste problema.

PRs #4 #6
