### ISSUE TITLE
PO migration está migrando incorretamente o style no angular.json

### ISSUE THREAD

**Issue by alvarocamillont** [portinariui/po-migration#2]
A ferramenta po migration , no angular.json na parte do style, está trocando 

node_modules/@totvs/thf-theme/css/thf-theme-default.min.css por node_modules/@portinari/style/css/portinari-theme-default.min.css quando o correto é 
./node_modules/@portinari/style/css/po-theme-default.min.css

**Comment by jhonyeduardo** [comment]
Boa tarde Alvaro, obrigado por reportar esta issue.

Atualizamos o pacote **po-migration@1.0.2** com a correção deste problema.

PRs #5  #6
